// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasColumnType("text").HasColumnName("action");
                    b.Property<string>("IpAddress").HasColumnType("text").HasColumnName("ip_address");
                    b.Property<string>("RoleUsed").HasColumnType("text").HasColumnName("role_used");
                    b.Property<DateTime>("Timestamp").HasColumnType("timestamp with time zone").HasColumnName("timestamp");
                    b.Property<Guid?>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("audit_logs");
                });

            modelBuilder.Entity("backend.Models.Badge", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("BadgeType").IsRequired().HasColumnType("text").HasColumnName("badge_type");
                    b.Property<DateTime>("GeneratedAt").HasColumnType("timestamp with time zone").HasColumnName("generated_at");
                    b.Property<DateTime?>("PrintedAt").HasColumnType("timestamp with time zone").HasColumnName("printed_at");
                    b.Property<string>("QrCodeData").HasColumnType("text").HasColumnName("qr_code_data");
                    b.Property<Guid>("VisitorId").HasColumnType("uuid").HasColumnName("visitor_id");
                    b.HasKey("Id");
                    b.HasIndex("VisitorId").IsUnique();
                    b.ToTable("badges");
                });

            modelBuilder.Entity("backend.Models.Host", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Department").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("department");
                    b.Property<string>("Email").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("email");
                    b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("name");
                    b.Property<Guid?>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.ToTable("hosts");
                });

            modelBuilder.Entity("backend.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                    b.Property<string>("TokenHash").IsRequired().HasColumnType("text").HasColumnName("token_hash");
                    b.Property<DateTime?>("UsedAt").HasColumnType("timestamp with time zone").HasColumnName("used_at");
                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("backend.Models.Session", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<DateTime>("ExpiresAt").HasColumnType("timestamp with time zone").HasColumnName("expires_at");
                    b.Property<string>("IpAddress").HasColumnType("text").HasColumnName("ip_address");
                    b.Property<bool>("IsPersistent").HasColumnType("boolean").HasColumnName("is_persistent");
                    b.Property<DateTime?>("RevokedAt").HasColumnType("timestamp with time zone").HasColumnName("revoked_at");
                    b.Property<string>("TokenHash").IsRequired().HasColumnType("text").HasColumnName("token_hash");
                    b.Property<Guid>("UserId").HasColumnType("uuid").HasColumnName("user_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.ToTable("sessions");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("email");
                    b.Property<int>("FailedAttempts").HasColumnType("integer").HasColumnName("failed_attempts");
                    b.Property<bool>("IsActive").HasColumnType("boolean").HasColumnName("is_active");
                    b.Property<DateTime?>("LockedUntil").HasColumnType("timestamp with time zone").HasColumnName("locked_until");
                    b.Property<string>("PasswordHash").IsRequired().HasColumnType("text").HasColumnName("password_hash");
                    b.Property<string>("Role").IsRequired().HasColumnType("text").HasColumnName("role");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.Property<string>("Username").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("username");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("Username").IsUnique();
                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Models.Visitor", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime?>("CheckInTime").HasColumnType("timestamp with time zone").HasColumnName("check_in_time");
                    b.Property<DateTime?>("CheckOutTime").HasColumnType("timestamp with time zone").HasColumnName("check_out_time");
                    b.Property<string>("Company").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("company");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone").HasColumnName("created_at");
                    b.Property<Guid?>("CreatedBy").HasColumnType("uuid").HasColumnName("created_by");
                    b.Property<Guid?>("HostId").HasColumnType("uuid").HasColumnName("host_id");
                    b.Property<string>("Name").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("name");
                    b.Property<string>("Purpose").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)").HasColumnName("purpose");
                    b.Property<DateTime?>("ScheduledTime").HasColumnType("timestamp with time zone").HasColumnName("scheduled_time");
                    b.Property<string>("Status").IsRequired().HasColumnType("text").HasColumnName("status");
                    b.Property<DateTime>("UpdatedAt").HasColumnType("timestamp with time zone").HasColumnName("updated_at");
                    b.HasKey("Id");
                    b.HasIndex("HostId");
                    b.ToTable("visitors");
                });

            modelBuilder.Entity("backend.Models.AuditLog", b =>
                {
                    b.HasOne("backend.Models.User", "User").WithMany("AuditLogs").HasForeignKey("UserId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Badge", b =>
                {
                    b.HasOne("backend.Models.Visitor", "Visitor").WithOne("Badge").HasForeignKey("backend.Models.Badge", "VisitorId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("backend.Models.PasswordResetToken", b =>
                {
                    b.HasOne("backend.Models.User", "User").WithMany("PasswordResetTokens").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Session", b =>
                {
                    b.HasOne("backend.Models.User", "User").WithMany("Sessions").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("backend.Models.Visitor", b =>
                {
                    b.HasOne("backend.Models.Host", "Host").WithMany("Visitors").HasForeignKey("HostId").OnDelete(DeleteBehavior.SetNull);
                    b.Navigation("Host");
                });

            modelBuilder.Entity("backend.Models.Host", b => { b.Navigation("Visitors"); });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Navigation("AuditLogs");
                    b.Navigation("PasswordResetTokens");
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("backend.Models.Visitor", b => { b.Navigation("Badge"); });
#pragma warning restore 612, 618
        }
    }
}
